id: who.fhir.smart-ig-empty
canonical: http://worldhealthorganization.github.io/smart
name: SMART
title: SMART Empty IG
description: An empty Implementation Guide to be used as a starting point for building SMART Guidelines Implementation Guides
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.3.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: WHO
  url: http://who.int
  # email: test@example.org


meta:
  profile:
    - SMARTImplementationGuide

pages:
  index.md:
    title: Home
    changes.md:
      title: Changes
    dependencies.md:
      title: Dependencies
    references.md:
      title: References
    adapting.md:
      title: Adapting Guidelines for Country use
    license.md:
      title: License
  business-requirements.md:
    title: Business Requirements
    concepts.md:
      title: Concepts
    personas.md:
      title: Generic Personas
    scenarios.md:
      title: User Scenarios
    business-processes.md:
      title: Business Processes
    dictionary.md:
      title: Data Dictionary
    decision-logic.md:
      title: Decision-support logic
    indicators.md:
      title: Indicator and Performance Metrics
    functional-requirements.md:
      title: Functional Requirements
    non-functional-requirements.md:
      title: Non-functional Requirements
  data-models-and-exchange.md:
    title: Data Models and Exchange
    system-actors.md:
      title: System Actors
    sequence-diagrams.md:
      title: Sequence Diagrams
    transactions.md:
      title: Transactions
#    logical-models.md:                                                                                                                                                   
#      title: Logical Models                                                                                                                                              
