id: who.fhir.smart-ig-empty
canonical: http://worldhealthorganization.github.io/smart
name: SMART
title: SMART Empty IG
description: An empty Implementation Guide to be used as a starting point for building SMART Guidelines Implementation Guides
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.3.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: WHO
  url: http://who.int
  # email: test@example.org


meta:
  profile:
    - SMARTImplementationGuide

pages:
  index.md:
    title: Home
    changes.md:
      title: Changes
    dependencies.md:
      title: Dependencies
    references.md:
      title: References
    adapting.md:
      title: Adapting Guidelines for Country use
    license.md:
      title: License
  business-requirements.md:
    title: Business Requirements
    concepts.md:
      title: Concepts
    personas.md:
      title: Generic Personas
    scenarios.md:
      title: User Scenarios
    business-processes.md:
      title: Business Processes
    dictionary.md:
      title: Data Dictionary
    decision-logic.md:
      title: Decision-support logic
    indicators.md:
      title: Indicator and Performance Metrics
    functional-requirements.md:
      title: Functional Requirements
    non-functional-requirements.md:
      title: Non-functional Requirements
  data-models-and-exchange.md:
    title: Data Models and Exchange
    system-actors.md:
      title: System Actors
    sequence-diagrams.md:
      title: Sequence Diagrams
    transactions.md:
      title: Transactions
#    logical-models.md:                                                                                                                                                   
#      title: Logical Models                                                                                                                                              
    indicators-measures.md:
      title: Indicators and Measures
#    profiles.xml:                                                                                                                                                        
#      title: Content profiles 
    codings.md:
      title: Codings
  deployment.md:
    title: Deployment
    security-privacy.md:
      title: Security and Privacy Considerations
    testing.md: 
      title: Testing
    test-data.md: 
      title: Test Data
    reference-implementations.md: 
      title: Reference Implementations
    trust_domain.md:
      title: Trust Domains
    downloads.md: 
      title: Downloads
  indices.md:
    title: Indices
    artifacts.html: 
      title: Artifact Index
    maps.md: 
      title: Mappings


menu:
  Home: 
    Summary: index.html
    Changes: changes.html
    Dependencies: dependencies.html
    References: references.html
    Adapting Guidelines for Country use: adapting.html
  Business Requirements: 
    Concepts: concepts.html
    Generic Personas: personas.html
    User Scenarios: scenarios.html
    Business Processes: business-processes.html
    Data Dictionary: dictionary.html
    Decision-support Logic: decision-logic.html
    Indicator and Performance Metrics: indicators.html
    Functional Requirements: functional-requirements.html
    Non-functional Requirements: non-functional-requirements.html
  Data Models and Exchange:
    System Actors: system-actors.html
    Sequence Diagrams: sequence-diagrams.html
    Transactions: transactions.html
    Indicators and Measures: indicators-measures.html
    Codings: codings.html

  Deployment:
    Security and Privacy Considerations: security-privacy.html
    Testing: testing.html
    Test Data: test-data.html
    Reference Implementations: reference-implementations.html
    Trust Domains: trust_domain.html
    Downloads: downloads.html

  Indices:
    Artifact Index: artifacts.html
    Mappings: maps.html
    
# ╭───────────────────────────Less Common Implementation Guide Properties──────────────────────────╮
# │  Uncomment the properties below to configure additional properties on the ImplementationGuide  │
# │  resource. These properties are less commonly needed than those above.                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#
# Those who need more control or want to add additional details to the contact values can use
# contact directly and follow the format outlined in the ImplementationGuide resource and
# ContactDetail.
#
# contact:
#   - name: Bob Smith
#     telecom:
#       - system: email # phone | fax | email | pager | url | sms | other
#         value: bobsmith@example.org
#         use: work
#
#
# The global property corresponds to the IG.global property, but it
# uses the type as the YAML key and the profile as its value. Since
# FHIR does not explicitly disallow more than one profile per type,
# neither do we; the value can be a single profile URL or an array
# of profile URLs. If a value is an id or name, SUSHI will replace
# it with the correct canonical when generating the IG JSON.
#
# global:
#   Patient: http://example.org/fhir/StructureDefinition/my-patient-profile
#   Encounter: http://example.org/fhir/StructureDefinition/my-encounter-profile
#
