id: who.fhir.smart-ig-empty
canonical: http://worldhealthorganization.github.io/smart
name: SMART
title: SMART Empty IG
description: An empty Implementation Guide to be used as a starting point for building SMART Guidelines Implementation Guides
